### ISSUE TITLE
Include CiviToken as a requirement

### ISSUE THREAD

**Issue by seamuslee001** [MegaphoneJon/com.megaphonetech.addressl10n#1]
@MegaphoneJon Jon given that this needs the CiviToken extension to properly work why not declare that it needs in the info.xml as per https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/info.xml#L23

**Comment by seamuslee001** [comment]
Actually ignore me wrong way around doh need more coffee closing

**Comment by MegaphoneJon** [comment]
I think it could actually be argued either way, and there's perhaps a stronger argument that this should declare the dependency - this extension is useless without Civitoken, but not vice versa.  I'll make the change.  Thanks @seamuslee001.
